DEBUG 2024-02-05 07:44:37.903 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-02-05 07:44:37.903 UTC: 	 Running on: Linux cms01.knu.ac.kr 3.10.0-1160.105.1.el7.x86_64 #1 SMP Thu Dec 7 15:39:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-02-05 07:44:37.903 UTC: 	 Executing command: 'status'
DEBUG 2024-02-05 07:44:37.908 UTC: 	 Found CRAB cache file /u/user/sha/.crab3
ERROR 2024-02-05 07:44:37.924 UTC: 	 Cannot find .requestcache file in CRAB project directory /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/UL2016_PreVFP/crab_DoubleMuon_Run2016B-ver2
ERROR 2024-02-05 07:44:37.925 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 678, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 525, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 519, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/UL2016_PreVFP/crab_DoubleMuon_Run2016B-ver2
INFO 2024-02-05 07:44:37.930 UTC: 	 Log file is /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/crab.log
DEBUG 2024-02-05 07:56:31.803 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-02-05 07:56:31.804 UTC: 	 Running on: Linux cms01.knu.ac.kr 3.10.0-1160.105.1.el7.x86_64 #1 SMP Thu Dec 7 15:39:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-02-05 07:56:31.804 UTC: 	 Executing command: 'status'
DEBUG 2024-02-05 07:56:31.812 UTC: 	 Found CRAB cache file /u/user/sha/.crab3
ERROR 2024-02-05 07:56:31.860 UTC: 	 Cannot find .requestcache file in CRAB project directory /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/UL2016_PreVFP/crab_DoubleMuon_Run2016B-ver2
ERROR 2024-02-05 07:56:31.860 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 678, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 525, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 519, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/UL2016_PreVFP/crab_DoubleMuon_Run2016B-ver2
INFO 2024-02-05 07:56:31.882 UTC: 	 Log file is /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/crab.log
DEBUG 2024-02-05 08:00:25.694 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-02-05 08:00:25.695 UTC: 	 Running on: Linux cms01.knu.ac.kr 3.10.0-1160.105.1.el7.x86_64 #1 SMP Thu Dec 7 15:39:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-02-05 08:00:25.695 UTC: 	 Executing command: 'status'
DEBUG 2024-02-05 08:00:25.698 UTC: 	 Found CRAB cache file /u/user/sha/.crab3
ERROR 2024-02-05 08:00:25.709 UTC: 	 Cannot find .requestcache file in CRAB project directory /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/UL2016_PreVFP/crab_DoubleMuon_Run2016B-ver2
ERROR 2024-02-05 08:00:25.710 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 678, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 525, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 519, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/UL2016_PreVFP/crab_DoubleMuon_Run2016B-ver2
INFO 2024-02-05 08:00:25.714 UTC: 	 Log file is /d0/scratch/sha/Analyses/SSB/MakeNtuples/Run2MiniAOD/v1p2/Develop/forGit/CMSSW_10_6_30/src/CMSAnalyses/SSBAnalyzer/Run2Crab_DATA/crab.log
